"""Hybrid figure preview widget for simulation plots and charts.

Combines an inline Unicode half-block thumbnail rendered in the terminal
with an external system viewer launcher (xdg-open) for inspecting high-resolution
figures, legends, and axes.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

from textual.widget import Widget

if TYPE_CHECKING:
    from textual.app import ComposeResult


class FigurePreview(Widget):
    """Interactive preview widget for figures generated by FlightLogger.

    Attributes:
        current_image_path: Path to the active image file being previewed.
    """

    def __init__(self, image_path: Path | None = None, **kwargs: Any) -> None:
        """Initialize the figure preview widget.

        Args:
            image_path: Optional path to an initial image file.
            **kwargs: Standard Textual widget keyword arguments.
        """
        super().__init__(**kwargs)
        self.current_image_path = image_path

    def compose(self) -> ComposeResult:
        """Render the thumbnail preview box and 'Open in Viewer' action trigger.

        Yields:
            Child widgets including thumbnail display and action button.
        """

    def load_figure(self, image_path: Path) -> None:
        """Load and render an inline thumbnail preview for a figure file.

        Args:
            image_path: Absolute or relative path to the image file (e.g. PNG).
        """

    def open_external_viewer(self) -> None:
        """Launch the operating system's default image viewer asynchronously."""
