name = "AGM-84_HARPOON"
description = "example created for demos"

[mass_properties]
type = "mass"
cg_from_nose_m = 2.05
cg_source = "AGM-84A baseline mass properties document"
total_mass_kg = 520.0

[propulsion.engine_3]
type = "turbojet_engine"
name = "Teledyne CAE J402-CA-400"
thrust_N = 2940.0
sfc_kg_per_Ns = 3.25e-5
mach_range = [ 0.2, 0.85,]
mass_flow_kg_per_s = 4.35
compression_ratio = 5.6
egt_K = 950.0
diameter_m = 0.318
length_m = 0.747
max_rpm = 41200.0

[propulsion.engine_4]
type = "solid_motor"
isp_vacuum_s = 255.0
isp_sl_s = 230.0
propellant_mass_kg = 70.0
burn_time_s = 2.9
thrust_mean_N = 53000.0
thrust_peak_N = 58000.0
propellant_density_kg_m3 = 1750.0
casing_length_m = 0.7
casing_diameter_m = 0.343

[aero_surfaces.aero_1]
type = "wing"
aspect_ratio = 2.3
sweep_deg = 45.0
taper_ratio = 0.2
span_m = 0.914
dihedral_deg = 0.0
airfoil_root = "NACA0006"
airfoil_tip = "NACA0006"
control_surfaces = []

[aero_surfaces.aero_2]
type = "fins"
count = 4
span_m = 0.285
sweep_deg = 60.0
chord_root_m = 0.75
chord_tip_m = 0.15
control_surfaces = []

[bodies.body_0]
type = "axisymmetric_body"
length_m = 3.84
diameter_m = 0.343
nose_type = "ogive"
nose_length_m = 0.75
nose_diameter_m = 0.343
total_length_m = 3.84
max_diameter_m = 0.343
