



  Performance statistics for DSP solver: icalls =      2

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          335838
     no. of nonzeroes in lower triangle of a =        21774543
     no. of nonzeroes in the factor l        =       104889507
     ratio of nonzeroes in factor (min/max)  =          0.7695
     number of super nodes                   =            8630
     maximum order of a front matrix         =            1695
     maximum size of a front matrix          =         1437360
     maximum size of a front trapezoid       =          895290
     no. of floating point ops for factor    =      4.6755D+10
     no. of floating point ops for solve     =      4.3093D+08
     ratio of flops for factor (min/max)     =          0.5235
     ratio of allocated memory (max/min)     =          1.4308
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.046875        0.056798
     time (cpu & wall) for ordering          =        0.343750        0.348947
     time (cpu & wall) for other matrix prep =        0.078125        0.076950
     time (cpu & wall) for value input       =        0.171875        0.180164
     time (cpu & wall) for matrix distrib.   =        0.609375        0.621784
     time (cpu & wall) for numeric factor    =        1.218750        1.243032
     computational rate (gflops) for factor  =       38.363377       37.613980
     time (cpu & wall) for numeric solve     =        0.078125        0.086413
     computational rate (gflops) for solve   =        5.515910        4.986888
     effective I/O rate (GB/sec) for solve   =       20.549996       18.579080

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        688128.        5. MB        671735.        5. MB
                95-   1        589824.        4. MB        580391.        4. MB
                95-   2        655360.        5. MB        623355.        5. MB
                95-   3        557056.        4. MB        538627.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:       2490368.       19. MB       2414108.       18. MB


  Solver Memory allocated on core    0       =      521.448 MB
  Solver Memory allocated on core    1       =      429.123 MB
  Solver Memory allocated on core    2       =      429.559 MB
  Solver Memory allocated on core    3       =      364.433 MB
  Total Solver Memory allocated by all cores =     1744.564 MB





  Performance statistics for DSP solver: icalls =      3

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          335838
     no. of nonzeroes in lower triangle of a =        21774543
     no. of nonzeroes in the factor l        =       104889507
     ratio of nonzeroes in factor (min/max)  =          0.7695
     number of super nodes                   =            8630
     maximum order of a front matrix         =            1695
     maximum size of a front matrix          =         1437360
     maximum size of a front trapezoid       =          895290
     no. of floating point ops for factor    =      4.6755D+10
     no. of floating point ops for solve     =      8.2776D+08
     ratio of flops for factor (min/max)     =          0.5235
     ratio of allocated memory (max/min)     =          1.4308
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.046875        0.047713
     time (cpu & wall) for ordering          =        0.359375        0.355515
     time (cpu & wall) for other matrix prep =        0.062500        0.067381
     time (cpu & wall) for value input       =        0.187500        0.180827
     time (cpu & wall) for matrix distrib.   =        0.578125        0.575030
     time (cpu & wall) for numeric factor    =        1.109375        1.106822
     computational rate (gflops) for factor  =       42.145682       42.242899
     time (cpu & wall) for numeric solve     =        0.078125        0.079204
     computational rate (gflops) for solve   =       10.595371       10.451030
     effective I/O rate (GB/sec) for solve   =       39.473966       38.936210

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        688128.        5. MB        671735.        5. MB
                95-   1        589824.        4. MB        580391.        4. MB
                95-   2        655360.        5. MB        623355.        5. MB
                95-   3        557056.        4. MB        538627.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:       2490368.       19. MB       2414108.       18. MB


  Solver Memory allocated on core    0       =      521.448 MB
  Solver Memory allocated on core    1       =      429.123 MB
  Solver Memory allocated on core    2       =      429.559 MB
  Solver Memory allocated on core    3       =      364.433 MB
  Total Solver Memory allocated by all cores =     1744.564 MB

